In [389]:
import pandas as pd
import os
import re
from datetime import datetime

## Read in SDTM IG Rules

In [390]:
home = os.path.expanduser("~")
ru = pd.read_excel(home + "/data/CORE/rules/SDTMIG Conformance Rules v3  FINAL.xlsx", sheet_name='SDTMIG Conformance Rules v3.0', skiprows=1)
ru.head(5)

,Rule ID,Rule ID Version,Related Rule(s),Rule Set,Team,Assigned To,Update Status,Discussion / Notes,Class,Subclass,...,Cited Doc,Cited Section,Cited Item,Cited Guidance,Release Notes,Jira Executability,CORE Programmability Status,CORE Programmability Comments,Historical: Programmable,Historical: Programmable Flag Comment
0,CG0001,1,NaN,3.2,NaN,NaN,NaN,NaN,ALL,NaN,...,IG v3.2,2.6,3.d,Check the CDISC Controlled Terminology [see Ap...,NaN,Fully Executable,Yes,"With access to CDISC Library, established doma...",Conditional,Dependent on additional non-CDISC metadata
1,CG0001,1,NaN,3.3,NaN,NaN,NaN,NaN,ALL,NaN,...,IG v3.3,2.6,3.e,"Determine the domain code, one that is not a d...",NaN,Fully Executable,Yes,"With access to CDISC Library, established doma...",Conditional,Dependent on additional non-CDISC metadata
2,CG0001,1,NaN,3.4,NaN,NaN,NaN,NaN,ALL,NaN,...,IG v3.4,3.2.2,NaN,Using SDTM-specified standard domain names and...,Section and cited guidance updated. Original ...,Fully Executable,Yes,"With access to CDISC Library, established doma...",Conditional,Dependent on additional non-CDISC metadata
3,CG0001,1,NaN,4.0,Final Review,Carlo,Final,NaN,ALL,NaN,...,IG v4.0,3.2,NaN,Using SDTM-specified standard domain names and...,Updated section number.,Fully Executable,Yes,"With access to CDISC Library, established doma...",Conditional,Dependent on additional non-CDISC metadata
4,CG0002,1,NaN,3.2,NaN,NaN,NaN,NaN,ALL,NaN,...,Model v1.4,2.2.5,NaN,"Collected duration of an event, intervention, ...",NaN,Fully Executable,NaN,NaN,Conditional,Dependent on additional appropriate metatdata

In [391]:
print(ru.shape)
ru_34 = ru[ru['Rule Set']==3.4].copy()
print(ru_34.shape)
ru_34.head(15)

(1839, 24)
(470, 24)

,Rule ID,Rule ID Version,Related Rule(s),Rule Set,Team,Assigned To,Update Status,Discussion / Notes,Class,Subclass,...,Cited Doc,Cited Section,Cited Item,Cited Guidance,Release Notes,Jira Executability,CORE Programmability Status,CORE Programmability Comments,Historical: Programmable,Historical: Programmable Flag Comment
2,CG0001,1,NaN,3.4,NaN,NaN,NaN,NaN,ALL,NaN,...,IG v3.4,3.2.2,NaN,Using SDTM-specified standard domain names and...,Section and cited guidance updated. Original ...,Fully Executable,Yes,"With access to CDISC Library, established doma...",Conditional,Dependent on additional non-CDISC metadata
6,CG0002,1,NaN,3.4,NaN,NaN,NaN,NaN,ALL,NaN,...,Model v2.0,Timing,--DUR,Used only if collected on the CRF and not deri...,Cited guidance updated. Reference to model sec...,Fully Executable,NaN,NaN,Conditional,Dependent on additional appropriate metatdata
10,CG0006,2,NaN,3.4,Final Review,Carlo,Final,replaced with new rule in 4.0,ALL,NaN,...,IG v3.4,4.4.4,NaN,The Study Day value is incremented by 1 for ea...,No Change; retired as of IG v4.0. replaced wit...,Fully Executable,NaN,NaN,Yes,NaN
14,CG0007,1,NaN,3.4,NaN,NaN,NaN,NaN,ALL,NaN,...,IG v3.4,4.4.4,NaN,"The permissible Study Day variables (--DY, --S...",NaN,Fully Executable,NaN,NaN,Yes,NaN
18,CG0008,1,NaN,3.4,NaN,NaN,NaN,NaN,ALL,NaN,...,Model v2.0,Timing,--ELTM,The interval of time between a planned time po...,Cited guidance updated. Reference to model sec...,Fully Executable,NaN,NaN,Yes,NaN
22,CG0009,1,NaN,3.4,NaN,NaN,NaN,NaN,ALL,NaN,...,IG v3.4,6.2.3,"DS, Assumption 4.c",EPOCH may be included as a timing variable as ...,No Change,Fully Executable,NaN,NaN,Yes,NaN
26,CG0010,3,NaN,3.4,Final Review,Carlo,Final,New version of rule.\n\nGEN removed from Varia...,ALL,NaN,...,IG v3.4,2.1,NaN,Each variable can be classified according to i...,"""Metadata attribute of"" added into the rule.",Fully Executable,NaN,NaN,Yes,NaN
30,CG0011,2,NaN,3.4,Final Review,Carlo,Final,New version of rule.\n\nGEN removed from Varia...,ALL,NaN,...,IG v3.4,3.2.2,NaN,Following SDTM-specified controlled terminolog...,No Change,Fully Executable,NaN,NaN,Yes,NaN
34,CG0012,2,,3.4,Final Review,Carlo,Final,New version of rule. \n\nSimplified to refer ...,ALL,NaN,...,IG v3.4|Model v2.0,IG v3.4[3.2.2]|Model v2.0[2.1],NaN,IG v3.4[3.2.2][Using SDTM-specified data types...,"""The SDTM describes the name, label, role, and...",Fully Executable,NaN,NaN,Yes,NaN
38,CG0013,2,NaN,3.4,Final Review,Carlo,Final,New version of rule.\n\nGEN removed from Varia...,ALL,NaN,...,IG v3.4|Model v2.0,2.5|Model Concepts and Terms --Variables|The G...,NaN,IG v3.4[2.5][Sponsors may not add any variable...,IG section number updated and citation clarifi...,Partially Executable,NaN,NaN,Yes,NaN
42,CG0014,2,NaN,3.4,Final Review,Carlo,Final,New version of rule.\n\nGEN removed from Varia...,ALL,NaN,...,IG v3.4,4.1.5,NaN,Required variables must always be included in ...,No Change,Fully Executable,NaN,NaN,Yes,NaN
46,CG0015,2,NaN,3.4,Final Review,Carlo,Final,New version of rule.\n\nGEN removed from Varia...,ALL,NaN,...,IG v3.4,4.1.5,NaN,If a study includes a data item that would be ...,Text for cited guidance was modified in SDTMIG...,Fully Executable,Conditional,Can be evaluated if Define-XML is present and ...,Conditional,Dependent on additional appropriate metatdata
50,CG0016,2,NaN,3.4,Final Review,Carlo,Final,New version of rule.\n\nGEN removed from Varia...,ALL,NaN,...,IG v3.4,4.1.5,NaN,When the study does not include the data item ...,Text for cited guidance was modified in SDTMIG...,Fully Executable,NaN,NaN,Yes,NaN
54,CG0017,3,NaN,3.4,NSV / Final Review,Carlo,Final,New version of rule.\n\nGEN removed from Varia...,NOT (AP),NaN,...,IG v3.4|AP Guide v1.0,4.1.7|2,Item 6,4.1.7[For domains with two-letter domain codes...,"Retired from IGs after v3.4, replaced by rule ...",Fully Executable,NaN,NaN,Yes,NaN
58,CG0018,2,NaN,3.4,Final Review,Carlo,Final,New version of rule.\n\nGEN removed from Varia...,ALL,NaN,...,IG v3.4,4.1.7,7,Supplemental Qualifier datasets for split doma...,No Change,Fully Executable,NaN,NaN,Yes,NaN

## Read in Collation of Rules

In [392]:
home = os.path.expanduser("~")
ruc = pd.read_excel(home + "/data/CORE/rules/Collation of Rule Editor Entries.xlsx", sheet_name='Rule Editor')
print(ruc.shape)
ruc.head(5)

(432, 22)

,Rule Id,Core \n Id,Core \n Version,Authority \n Organization,Standards \n Name,Standards \n Version,Rule Identifier \n Id,Rule Identifier \n Rule Version,Rule Identifier \n Conformance Guide Version,Description,...,Rule Type,Check,Match Datasets,Operations,Outcome \n Message,Outcome \n Output Variables,Citations,References \n Origin,Sensitivity,Severity
0,CG0001,CDISC.SDTMIG.CG0001,1,CDISC,SDTMIG,3.4,CG0001,1,2,DOMAIN name should use a SDTM-specified standa...,...,Range & Limit,all:\n - name: DOMAIN\n operator: uses_valid_c...,NaN,NaN,DOMAIN Code is not a published DOMAIN Code in ...,NaN,- Cited Guidance: Using SDTM-specified standar...,SDTM and SDTMIG Conformance Rules,Record,Notice
1,CG0002,CDISC.SDTMIG.CG0002,1,CDISC,SDTMIG,3.4,CG0002,1,2,Raise a message when --DUR exists in a dataset...,...,Variable Presence,all:\n - name: --DUR\n operator: exists\n,NaN,NaN,"--DUR exists in a dataset, confirm collected a...",NaN,- Cited Guidance: Used only if collected on th...,SDTM and SDTMIG Conformance Rules,Dataset,Warning
2,CG0006,CDISC.SDTMIG.CG0006,1,CDISC,SDTMIG,3.4,CG0006,2,2,Raise an error when --DY is not calculated as ...,...,Value Presence,all:\n - name: --DY\n operator: non_empty\n - ...,- Name: DM\n Keys:\n - USUBJID\n,- name: --DTC\n operator: dy # does dy op take...,--DY is not calculated correctly even though t...,- --DY - --DTC - RFSTDTC,- Cited Guidance: The Study Day value is incre...,SDTM and SDTMIG Conformance Rules,Record,Error
3,CG0007,CDISC.SDTMIG.CG0007,1,CDISC,SDTMIG,3.4,CG0007,1,2,Raise an error when the date portion of --DTC ...,...,Value Presence,all:\n - name: --DY\n operator: non_empty\n - ...,- Name: DM\n Keys:\n - USUBJID\n,NaN,The date portion of --DTC is not complete date...,- --DY - --DTC - RFSTDTC,- Cited Guidance: The permissible Study Day va...,SDTM and SDTMIG Conformance Rules,Record,Error
4,CG0008,CDISC.SDTMIG.CG0008,1,CDISC,SDTMIG,3.4,CG0008,1,2,"Raise an error when --TPTREF is empty, but --E...",...,Value Presence,all:\n - name: --TPTREF\n operator: empty\n - ...,NaN,NaN,--TPTREF is empty and --ELTM is not empty,- --TPTREF - --ELTM,- Cited Guidance: The interval of time between...,SDTM and SDTMIG Conformance Rules,Record,Error

In [393]:
me = ruc.merge(ru_34, how="outer", left_on="Rule Id", right_on="Rule ID")
print(me.shape)
me.head(5)

(485, 46)

,Rule Id,Core \n Id,Core \n Version,Authority \n Organization,Standards \n Name,Standards \n Version,Rule Identifier \n Id,Rule Identifier \n Rule Version,Rule Identifier \n Conformance Guide Version,Description,...,Cited Doc,Cited Section,Cited Item,Cited Guidance,Release Notes,Jira Executability,CORE Programmability Status,CORE Programmability Comments,Historical: Programmable,Historical: Programmable Flag Comment
0,CG0001,CDISC.SDTMIG.CG0001,1.0,CDISC,SDTMIG,3.4,CG0001,1.0,2.0,DOMAIN name should use a SDTM-specified standa...,...,IG v3.4,3.2.2,NaN,Using SDTM-specified standard domain names and...,Section and cited guidance updated. Original ...,Fully Executable,Yes,"With access to CDISC Library, established doma...",Conditional,Dependent on additional non-CDISC metadata
1,CG0002,CDISC.SDTMIG.CG0002,1.0,CDISC,SDTMIG,3.4,CG0002,1.0,2.0,Raise a message when --DUR exists in a dataset...,...,Model v2.0,Timing,--DUR,Used only if collected on the CRF and not deri...,Cited guidance updated. Reference to model sec...,Fully Executable,NaN,NaN,Conditional,Dependent on additional appropriate metatdata
2,CG0006,CDISC.SDTMIG.CG0006,1.0,CDISC,SDTMIG,3.4,CG0006,2.0,2.0,Raise an error when --DY is not calculated as ...,...,IG v3.4,4.4.4,NaN,The Study Day value is incremented by 1 for ea...,No Change; retired as of IG v4.0. replaced wit...,Fully Executable,NaN,NaN,Yes,NaN
3,CG0007,CDISC.SDTMIG.CG0007,1.0,CDISC,SDTMIG,3.4,CG0007,1.0,2.0,Raise an error when the date portion of --DTC ...,...,IG v3.4,4.4.4,NaN,"The permissible Study Day variables (--DY, --S...",NaN,Fully Executable,NaN,NaN,Yes,NaN
4,CG0008,CDISC.SDTMIG.CG0008,1.0,CDISC,SDTMIG,3.4,CG0008,1.0,2.0,"Raise an error when --TPTREF is empty, but --E...",...,Model v2.0,Timing,--ELTM,The interval of time between a planned time po...,Cited guidance updated. Reference to model sec...,Fully Executable,NaN,NaN,Yes,NaN

## Read in current Regression

In [394]:
reg = pd.read_json("/Users/verisian/code/core-regression-dashboard/data/2025-11-20-rules.json")
print(reg['standard_source'].unique().tolist())
reg = reg[reg['standard_source']=='SDTMIG']
print(reg['standard_source'].unique().tolist())
print(reg.shape)
reg.head(200)

['ADAMIG', 'SDTMIG', 'define']
['SDTMIG']
(640, 17)

,core-id,cdisc_rule_id,standard,executability,status,standard_source,core_id_is_null,core_id_startswith_CORE,in_cache,rule_in_mltple_standards,check_operators,sharepoint_source,negative_folder_path,negative_regressions,positive_folder_path,positive_regressions,error
114,CDISC.SDTMIG.CG0001,"CG0001, TIG0289, SEND16, TIG0090","SDTMIG, TIG, SENDIG, SENDIG-DART, SENDIG-GENETOX",Fully Executable,Draft,SDTMIG,0.0,0.0,0.0,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN
115,CDISC.SDTMIG.CG0002,CG0002,SDTMIG,Fully Executable,Draft,SDTMIG,0.0,0.0,0.0,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN
116,CDISC.SDTMIG.CG0010,CG0010,SDTMIG,Partially Executable - Possible Underreporting,Draft,SDTMIG,0.0,0.0,0.0,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN
117,CDISC.SDTMIG.CG0012,"CG0012, SEND4","SDTMIG, SENDIG, SENDIG-GENETOX, SENDIG-DART",Fully Executable,Draft,SDTMIG,0.0,0.0,0.0,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN
118,CDISC.SDTMIG.CG0015,CG0015,SDTMIG,Fully Executable,Draft,SDTMIG,0.0,0.0,0.0,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313,CORE-000084,"CG0057, TIG0331","SDTMIG, TIG",Fully Executable,Published,SDTMIG,0.0,1.0,1.0,[],"[exists, not_exists]",SDTMIG,SDTMIG/CG0057/negative,[{'SDTMIG/CG0057/negative/01': {'test_case_xsl...,SDTMIG/CG0057/positive,[{'SDTMIG/CG0057/positive/01': {'test_case_xsl...,NaN
314,CORE-000085,"CG0059, TIG0333","SDTMIG, TIG",Fully Executable,Published,SDTMIG,0.0,1.0,1.0,[],"[empty, non_empty]",SDTMIG,SDTMIG/CG0059/negative,[{'SDTMIG/CG0059/negative/01': {'test_case_xsl...,SDTMIG/CG0059/positive,[{'SDTMIG/CG0059/positive/01': {'test_case_xsl...,NaN
315,CORE-000086,"CG0075, TIG0341","SDTMIG, TIG",Fully Executable,Published,SDTMIG,0.0,1.0,1.0,[],[date_less_than],SDTMIG,SDTMIG/CG0075/negative,[{'SDTMIG/CG0075/negative/01': {'test_case_xsl...,SDTMIG/CG0075/positive,[{'SDTMIG/CG0075/positive/01': {'test_case_xsl...,NaN
316,CORE-000087,"CG0387, TIG0549","SDTMIG, TIG",Fully Executable,Published,SDTMIG,0.0,1.0,1.0,[],"[is_not_contained_by, non_empty]",SDTMIG,SDTMIG/CG0387/negative,[{'SDTMIG/CG0387/negative/01': {'test_case_xsl...,SDTMIG/CG0387/positive,[{'SDTMIG/CG0387/positive/01': {'test_case_xsl...,NaN
317,CORE-000088,"CG0149, SEND25, TIG0169, TIG0390","SDTMIG, SENDIG, SENDIG-DART, SENDIG-GENETOX, TIG",Fully Executable,Published,SDTMIG,0.0,1.0,1.0,[],[matches_regex],SDTMIG,SDTMIG/CG0149/negative,[{'SDTMIG/CG0149/negative/01': {'test_case_xsl...,SDTMIG/CG0149/positive,[{'SDTMIG/CG0149/positive/01': {'test_case_xsl...,NaN

In [395]:
def v_stat(row):
    if not pd.isna(row['error']):
        return 'error'
    if isinstance(row['negative_regressions'], list):
        response = []
        for tc in row['negative_regressions']:
            for k,v in tc.items():
                engine_regression = v.get("engine_regression")
                if engine_regression:
                    response.append(engine_regression.get("sql_overall_result"))
                else:
                    response.append('not success')
        if all(x == "success" for x in response):
            return 'success'
        else:
            return 'failing'
    return 'no test data'

reg["verisian_status"] = reg.apply(lambda row: v_stat(row), axis=1)
reg.head(200)

,core-id,cdisc_rule_id,standard,executability,status,standard_source,core_id_is_null,core_id_startswith_CORE,in_cache,rule_in_mltple_standards,check_operators,sharepoint_source,negative_folder_path,negative_regressions,positive_folder_path,positive_regressions,error,verisian_status
114,CDISC.SDTMIG.CG0001,"CG0001, TIG0289, SEND16, TIG0090","SDTMIG, TIG, SENDIG, SENDIG-DART, SENDIG-GENETOX",Fully Executable,Draft,SDTMIG,0.0,0.0,0.0,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,no test data
115,CDISC.SDTMIG.CG0002,CG0002,SDTMIG,Fully Executable,Draft,SDTMIG,0.0,0.0,0.0,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,no test data
116,CDISC.SDTMIG.CG0010,CG0010,SDTMIG,Partially Executable - Possible Underreporting,Draft,SDTMIG,0.0,0.0,0.0,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,no test data
117,CDISC.SDTMIG.CG0012,"CG0012, SEND4","SDTMIG, SENDIG, SENDIG-GENETOX, SENDIG-DART",Fully Executable,Draft,SDTMIG,0.0,0.0,0.0,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,no test data
118,CDISC.SDTMIG.CG0015,CG0015,SDTMIG,Fully Executable,Draft,SDTMIG,0.0,0.0,0.0,[],NaN,NaN,NaN,NaN,NaN,NaN,NaN,no test data
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313,CORE-000084,"CG0057, TIG0331","SDTMIG, TIG",Fully Executable,Published,SDTMIG,0.0,1.0,1.0,[],"[exists, not_exists]",SDTMIG,SDTMIG/CG0057/negative,[{'SDTMIG/CG0057/negative/01': {'test_case_xsl...,SDTMIG/CG0057/positive,[{'SDTMIG/CG0057/positive/01': {'test_case_xsl...,NaN,success
314,CORE-000085,"CG0059, TIG0333","SDTMIG, TIG",Fully Executable,Published,SDTMIG,0.0,1.0,1.0,[],"[empty, non_empty]",SDTMIG,SDTMIG/CG0059/negative,[{'SDTMIG/CG0059/negative/01': {'test_case_xsl...,SDTMIG/CG0059/positive,[{'SDTMIG/CG0059/positive/01': {'test_case_xsl...,NaN,success
315,CORE-000086,"CG0075, TIG0341","SDTMIG, TIG",Fully Executable,Published,SDTMIG,0.0,1.0,1.0,[],[date_less_than],SDTMIG,SDTMIG/CG0075/negative,[{'SDTMIG/CG0075/negative/01': {'test_case_xsl...,SDTMIG/CG0075/positive,[{'SDTMIG/CG0075/positive/01': {'test_case_xsl...,NaN,success
316,CORE-000087,"CG0387, TIG0549","SDTMIG, TIG",Fully Executable,Published,SDTMIG,0.0,1.0,1.0,[],"[is_not_contained_by, non_empty]",SDTMIG,SDTMIG/CG0387/negative,[{'SDTMIG/CG0387/negative/01': {'test_case_xsl...,SDTMIG/CG0387/positive,[{'SDTMIG/CG0387/positive/01': {'test_case_xsl...,NaN,success
317,CORE-000088,"CG0149, SEND25, TIG0169, TIG0390","SDTMIG, SENDIG, SENDIG-DART, SENDIG-GENETOX, TIG",Fully Executable,Published,SDTMIG,0.0,1.0,1.0,[],[matches_regex],SDTMIG,SDTMIG/CG0149/negative,[{'SDTMIG/CG0149/negative/01': {'test_case_xsl...,SDTMIG/CG0149/positive,[{'SDTMIG/CG0149/positive/01': {'test_case_xsl...,NaN,success

In [396]:
def v_val(row):
    if not pd.isna(row['error']):
        return 'error'
    if isinstance(row['negative_regressions'], list):
        response = []
        for tc in row['negative_regressions']:
            for k,v in tc.items():
                engine_regression = v.get("engine_regression")
                if engine_regression:
                    response.append(engine_regression.get("sql_results_validation"))
                else:
                    return 'missing'
        if all(x == "success" for x in response):
            return 'valid'
        else:
            return 'invalid'
    return 'missing'
reg["verisian_validity"] = reg.apply(lambda row: v_val(row), axis=1)

def cg_id(row):
    if row['negative_folder_path']:
        return row['negative_folder_path'].split('/')[1]
    else:
        return ""

reg['negative_folder_path'] = reg['negative_folder_path'].fillna("")
reg['cg_rule_id'] = reg.apply(lambda row: cg_id(row), axis=1)

reg.head(200)

,core-id,cdisc_rule_id,standard,executability,status,standard_source,core_id_is_null,core_id_startswith_CORE,in_cache,rule_in_mltple_standards,check_operators,sharepoint_source,negative_folder_path,negative_regressions,positive_folder_path,positive_regressions,error,verisian_status,verisian_validity,cg_rule_id
114,CDISC.SDTMIG.CG0001,"CG0001, TIG0289, SEND16, TIG0090","SDTMIG, TIG, SENDIG, SENDIG-DART, SENDIG-GENETOX",Fully Executable,Draft,SDTMIG,0.0,0.0,0.0,[],NaN,NaN,,NaN,NaN,NaN,NaN,no test data,missing,
115,CDISC.SDTMIG.CG0002,CG0002,SDTMIG,Fully Executable,Draft,SDTMIG,0.0,0.0,0.0,[],NaN,NaN,,NaN,NaN,NaN,NaN,no test data,missing,
116,CDISC.SDTMIG.CG0010,CG0010,SDTMIG,Partially Executable - Possible Underreporting,Draft,SDTMIG,0.0,0.0,0.0,[],NaN,NaN,,NaN,NaN,NaN,NaN,no test data,missing,
117,CDISC.SDTMIG.CG0012,"CG0012, SEND4","SDTMIG, SENDIG, SENDIG-GENETOX, SENDIG-DART",Fully Executable,Draft,SDTMIG,0.0,0.0,0.0,[],NaN,NaN,,NaN,NaN,NaN,NaN,no test data,missing,
118,CDISC.SDTMIG.CG0015,CG0015,SDTMIG,Fully Executable,Draft,SDTMIG,0.0,0.0,0.0,[],NaN,NaN,,NaN,NaN,NaN,NaN,no test data,missing,
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
313,CORE-000084,"CG0057, TIG0331","SDTMIG, TIG",Fully Executable,Published,SDTMIG,0.0,1.0,1.0,[],"[exists, not_exists]",SDTMIG,SDTMIG/CG0057/negative,[{'SDTMIG/CG0057/negative/01': {'test_case_xsl...,SDTMIG/CG0057/positive,[{'SDTMIG/CG0057/positive/01': {'test_case_xsl...,NaN,success,invalid,CG0057
314,CORE-000085,"CG0059, TIG0333","SDTMIG, TIG",Fully Executable,Published,SDTMIG,0.0,1.0,1.0,[],"[empty, non_empty]",SDTMIG,SDTMIG/CG0059/negative,[{'SDTMIG/CG0059/negative/01': {'test_case_xsl...,SDTMIG/CG0059/positive,[{'SDTMIG/CG0059/positive/01': {'test_case_xsl...,NaN,success,invalid,CG0059
315,CORE-000086,"CG0075, TIG0341","SDTMIG, TIG",Fully Executable,Published,SDTMIG,0.0,1.0,1.0,[],[date_less_than],SDTMIG,SDTMIG/CG0075/negative,[{'SDTMIG/CG0075/negative/01': {'test_case_xsl...,SDTMIG/CG0075/positive,[{'SDTMIG/CG0075/positive/01': {'test_case_xsl...,NaN,success,invalid,CG0075
316,CORE-000087,"CG0387, TIG0549","SDTMIG, TIG",Fully Executable,Published,SDTMIG,0.0,1.0,1.0,[],"[is_not_contained_by, non_empty]",SDTMIG,SDTMIG/CG0387/negative,[{'SDTMIG/CG0387/negative/01': {'test_case_xsl...,SDTMIG/CG0387/positive,[{'SDTMIG/CG0387/positive/01': {'test_case_xsl...,NaN,success,invalid,CG0387
317,CORE-000088,"CG0149, SEND25, TIG0169, TIG0390","SDTMIG, SENDIG, SENDIG-DART, SENDIG-GENETOX, TIG",Fully Executable,Published,SDTMIG,0.0,1.0,1.0,[],[matches_regex],SDTMIG,SDTMIG/CG0149/negative,[{'SDTMIG/CG0149/negative/01': {'test_case_xsl...,SDTMIG/CG0149/positive,[{'SDTMIG/CG0149/positive/01': {'test_case_xsl...,NaN,success,invalid,CG0149

## merge regression

In [397]:
reg = reg[['core-id', 'cdisc_rule_id', 'check_operators', 'verisian_status', 'verisian_validity', 'cg_rule_id']].copy()
merged = me.merge(reg, left_on='Rule Id', right_on='cg_rule_id', how='outer')
merged.head()

,Rule Id,Core \n Id,Core \n Version,Authority \n Organization,Standards \n Name,Standards \n Version,Rule Identifier \n Id,Rule Identifier \n Rule Version,Rule Identifier \n Conformance Guide Version,Description,...,CORE Programmability Status,CORE Programmability Comments,Historical: Programmable,Historical: Programmable Flag Comment,core-id,cdisc_rule_id,check_operators,verisian_status,verisian_validity,cg_rule_id
0,CG0001,CDISC.SDTMIG.CG0001,1.0,CDISC,SDTMIG,3.4,CG0001,1.0,2.0,DOMAIN name should use a SDTM-specified standa...,...,Yes,"With access to CDISC Library, established doma...",Conditional,Dependent on additional non-CDISC metadata,NaN,NaN,NaN,NaN,NaN,NaN
1,CG0002,CDISC.SDTMIG.CG0002,1.0,CDISC,SDTMIG,3.4,CG0002,1.0,2.0,Raise a message when --DUR exists in a dataset...,...,NaN,NaN,Conditional,Dependent on additional appropriate metatdata,NaN,NaN,NaN,NaN,NaN,NaN
2,CG0006,CDISC.SDTMIG.CG0006,1.0,CDISC,SDTMIG,3.4,CG0006,2.0,2.0,Raise an error when --DY is not calculated as ...,...,NaN,NaN,Yes,NaN,CORE-000529,"CG0006, TIG0291, SEND73, TIG0274, SEND74, TIG0...","[is_complete_date, non_empty, not_equal_to]",failing,invalid,CG0006
3,CG0007,CDISC.SDTMIG.CG0007,1.0,CDISC,SDTMIG,3.4,CG0007,1.0,2.0,Raise an error when the date portion of --DTC ...,...,NaN,NaN,Yes,NaN,CORE-000354,"CG0007, TIG0292","[is_incomplete_date, non_empty]",failing,invalid,CG0007
4,CG0008,CDISC.SDTMIG.CG0008,1.0,CDISC,SDTMIG,3.4,CG0008,1.0,2.0,"Raise an error when --TPTREF is empty, but --E...",...,NaN,NaN,Yes,NaN,CORE-000028,"CG0008, TIG0293","[empty, non_empty]",success,invalid,CG0008

In [398]:
merged.value_counts(["Rule Type"])

Rule Type
Range & Limit                                 108
Variable Presence                              91
Value Presence                                 88
Consistency                                    33
Uniqueness                                     25
Relationship Integrity Check                   21
External Dictionaries                          13
Domain Presence Check                          10
Variable Length                                 9
Variable Metadata Check                         8
Populated Values                                8
Functional Dependency                           6
Data Pattern and Format                         4
Date Arithmetic                                 3
Variable Metadata Check against Define XML      3
Domain Existence Check                          2
Dataset Metadata Check                          2
Dataset Metadata Check against Define XML       1
Name: count, dtype: int64

In [399]:
merged["verisian_comment"] = ''
merged["verisian_status"] = merged["verisian_status"].astype(str)
merged["verisian_status"] = merged["verisian_status"].str.replace("nan", "not implemented")
merged['Rule Type'] = merged['Rule Type'].fillna("UNKNOWN")
merged.columns = [col.strip() for col in merged.columns]
merged.columns = [re.sub(r'[^A-Za-z0-9()]+', '_', col) for col in merged.columns]
merged.columns

Index(['Rule_Id', 'Core_Id', 'Core_Version', 'Authority_Organization',
       'Standards_Name', 'Standards_Version', 'Rule_Identifier_Id',
       'Rule_Identifier_Rule_Version',
       'Rule_Identifier_Conformance_Guide_Version', 'Description',
       'Scopes_Classes', 'Scopes_Domains', 'Rule_Type', 'Check',
       'Match_Datasets', 'Operations', 'Outcome_Message',
       'Outcome_Output_Variables', 'Citations', 'References_Origin',
       'Sensitivity', 'Severity', 'Rule_ID', 'Rule_ID_Version',
       'Related_Rule(s)', 'Rule_Set', 'Team', 'Assigned_To', 'Update_Status',
       'Discussion_Notes', 'Class', 'Subclass', 'Dataset_or_Domain',
       'Variable', 'Condition', 'Rule', 'Cited_Doc', 'Cited_Section',
       'Cited_Item', 'Cited_Guidance', 'Release_Notes', 'Jira_Executability',
       'CORE_Programmability_Status', 'CORE_Programmability_Comments',
       'Historical_Programmable', 'Historical_Programmable_Flag_Comment',
       'core_id', 'cdisc_rule_id', 'check_operators', 'verisian_status',
       'verisian_validity', 'cg_rule_id', 'verisian_comment'],
      dtype='object')

In [400]:
ordered = [
    'Rule_Id', 'Core_Id', 'Rule_ID', 'Rule_ID_Version', 'Rule_Identifier_Id', 'Rule_Identifier_Rule_Version',
    'Authority_Organization', 'Standards_Name', 'Standards_Version', 'Rule_Identifier_Conformance_Guide_Version',
    'Cited_Item', 'Cited_Guidance', 'Cited_Doc', 'Cited_Section', 'Release_Notes', 'Citations', 'References_Origin', 'Sensitivity', 'Severity',

    'verisian_comment', 'verisian_status', 'verisian_validity',
    'Description', 'Outcome_Message', 'Discussion_Notes', 'Rule_Type',
    'Variable', 'Condition', 'Rule',
    'Scopes_Classes', 'Scopes_Domains', 'Class', 'Subclass', 'Dataset_or_Domain',
    'Check', 'Match_Datasets', 'Operations',
    'Outcome_Output_Variables',

    'Related_Rule(s)', 'Rule_Set',

    'Jira_Executability', 'Team', 'Assigned_To', 'Update_Status',
    'CORE_Programmability_Status', 'CORE_Programmability_Comments',
    'Historical_Programmable', 'Historical_Programmable_Flag_Comment','Core_Version'
       ]
merged = merged[ordered].copy()

In [401]:
merged.dtypes

Rule_Id                                       object
Core_Id                                       object
Rule_ID                                       object
Rule_ID_Version                              float64
Rule_Identifier_Id                            object
Rule_Identifier_Rule_Version                 float64
Authority_Organization                        object
Standards_Name                                object
Standards_Version                            float64
Rule_Identifier_Conformance_Guide_Version    float64
Cited_Item                                    object
Cited_Guidance                                object
Cited_Doc                                     object
Cited_Section                                 object
Release_Notes                                 object
Citations                                     object
References_Origin                             object
Sensitivity                                   object
Severity                                      object
verisian_comment                              object
verisian_status                               object
verisian_validity                             object
Description                                   object
Outcome_Message                               object
Discussion_Notes                              object
Rule_Type                                     object
Variable                                      object
Condition                                     object
Rule                                          object
Scopes_Classes                                object
Scopes_Domains                                object
Class                                         object
Subclass                                     float64
Dataset_or_Domain                             object
Check                                         object
Match_Datasets                                object
Operations                                    object
Outcome_Output_Variables                      object
Related_Rule(s)                               object
Rule_Set                                     float64
Jira_Executability                            object
Team                                          object
Assigned_To                                   object
Update_Status                                 object
CORE_Programmability_Status                   object
CORE_Programmability_Comments                 object
Historical_Programmable                       object
Historical_Programmable_Flag_Comment          object
Core_Version                                 float64
dtype: object

In [402]:
merged = merged.sort_values(by=["verisian_status"], ascending=True).copy()

date = str(datetime.today().date())
if not os.path.exists(date):
    os.mkdir(date)
for value, group in merged.groupby("Rule_Type"):
    cleaned = re.sub(r"[^A-Za-z0-9_-]+", "_", str(value))
    filename = f"{date}/{cleaned}.csv".lower()
    group.to_csv(filename, index=False, header=True)

## Read in FDA Rules

In [403]:
home = os.path.expanduser("~")
ruc = pd.read_excel(home + "/data/CORE/rules/FDA_Business_Rules_Harmonized Rules Catalog Spreadsheet.xlsx", sheet_name='Rules Catalog', skiprows=1)
print(ruc.shape)
ruc.head(5)

(289, 40)

/Users/verisian/.pyenv/versions/verisian-core/lib/python3.12/site-packages/openpyxl/worksheet/_reader.py:329: UserWarning: Data Validation extension is not supported and will be removed
  warn(msg)

,Rule ID,Rule ID Version (represents any change to the rule)\n,"Related Rule(s) [See Also, Compare Against]","Rule Set (Generally IG Version, OCCDS v1.0, ADNCA v1.0)",Class,Subclass,Dataset or Domain,Variable,Element,Scope Section,...,Cited Document,Cited Section,"Cited Item (text, figure, table, footnote)","Cited Guidance (start with variable you are referring to if, for example it is from CDISC Notes)",Guidance Section,Release Notes,Author,Question(s) for FDA,Answer of the FDA,Authoring section
0,FB0101,1,NaN,NaN,REL,NaN,SUPPAE,AETRTEM,NaN,NaN,...,FDA Business Rules v1.5,FDAB001,NaN,A treatment-emergent flag should be submitted.,NaN,NaN,Nick,NaN,NaN,NaN
1,FB0301,1,NaN,NaN,EVT,NaN,AE,NaN,NaN,NaN,...,FDA Business Rules v1.5,FDAB003,NaN,Adverse events should be coded using the most ...,NaN,NaN,Anthony,NaN,NaN,NaN
2,FB0401,1,NaN,NaN,SPC,NaN,SE,NaN,,NaN,...,FDA Business Rules v1.5,FDAB004,NaN,"AE, CE, CM, DS, EG, EX, LB, MH, PC, PP, SE, SV...",NaN,NaN,Mandar,NaN,NaN,NaN
3,FB0402,1,NaN,NaN,EVT,NaN,AE,NaN,,NaN,...,FDA Business Rules v1.5,FDAB004,NaN,"AE, CE, CM, DS, EG, EX, LB, MH, PC, PP, SE, SV...",NaN,NaN,Mandar,NaN,NaN,NaN
4,FB0403,1,NaN,NaN,EVT,NaN,DS,NaN,,NaN,...,FDA Business Rules v1.5,FDAB004,NaN,"AE, CE, CM, DS, EG, EX, LB, MH, PC, PP, SE, SV...",NaN,NaN,Mandar,NaN,NaN,NaN